# Generated by Django 4.2.1 on 2023-07-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_location_alter_restaurant_latitude_and_more'),
        ('menu', '0002_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='rest_id',
            field=models.ForeignKey(db_column='rest_id', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
