# Generated by Django 4.2.1 on 2023-06-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='맛있어요', max_length=100),
        ),
    ]
