# Generated by Django 4.2.1 on 2023-07-07 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Review_id',
            new_name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.ImageField(upload_to='')),
                ('email', models.ForeignKey(db_column='user', default='admin@admin.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
                ('review', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='review.review')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
    ]
