# Generated by Django 4.2.1 on 2023-07-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_address'),
        ('review', '0003_rename_review_id_review_review_id_review_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rest_id',
            field=models.ForeignKey(db_column='rest_id', on_delete=django.db.models.deletion.CASCADE, related_name='rest_rev', to='restaurant.restaurant'),
        ),
    ]
