# Generated by Django 4.2.1 on 2023-07-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_photos_email_alter_review_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='email',
            new_name='user',
        ),
    ]
