# Generated by Django 4.2.1 on 2023-06-23 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_rest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
