# Generated by Django 4.2.1 on 2023-07-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hjd', '0003_hjd_latitude_hjd_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('location', models.ForeignKey(db_column='location', null=True, on_delete=django.db.models.deletion.PROTECT, to='hjd.hjd', to_field='adm_nm')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
