# Generated by Django 4.2.1 on 2023-07-12 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hjd', '0002_alter_hjd_adm_nm'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(db_column='location', null=True, on_delete=django.db.models.deletion.PROTECT, to='hjd.hjd', to_field='adm_nm'),
        ),
    ]
