# Generated by Django 4.2.1 on 2023-06-23 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_alter_restaurant_rest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('regist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('address', models.CharField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('category_name', models.ForeignKey(db_column='category_name', default='한식', on_delete=django.db.models.deletion.CASCADE, to='restaurant.categories', to_field='category_name')),
                ('user', models.ForeignKey(db_column='user', default='admin@admin.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
