# Generated by Django 4.2.1 on 2023-07-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hjd',
            name='adm_nm',
            field=models.CharField(unique=True),
        ),
    ]
