# Generated by Django 4.2.1 on 2023-07-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjd', '0002_alter_hjd_adm_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='hjd',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hjd',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
