# Generated by Django 4.2.1 on 2023-08-21 23:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hjd', '0003_hjd_latitude_hjd_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hjd',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
