# Generated by Django 4.2.1 on 2023-06-28 23:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0003_alter_restaurant_rest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_no', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('amount', models.IntegerField()),
                ('content', models.TextField(null=True)),
                ('rest_id', models.ForeignKey(db_column='rest_id', default='9e439580-d563-44fc-83d0-9da15ca2a872', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
