# Generated by Django 4.2.1 on 2023-07-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_location_alter_restaurant_latitude_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='rest_id',
            field=models.ForeignKey(db_column='rest_id', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
